// src/lib/components/LLMChatPanel.svelte
<script>
  import { onMount, onDestroy, afterUpdate } from 'svelte';
  import { chatStore } from '$lib/stores/chat.js';
  import { resourcesStore } from '$lib/stores/resources.js';
  import { sendChatMessage } from '$lib/services/llmChatService.js';
  import { processMarkdownWithRcLinks } from '$lib/utils/markdownUtils.js';
  import { enhanceLLMResponse } from '$lib/utils/emojiEnhancer.js';
  import { extractVerseText, extractChapterText, validateCleanText, emergencyUSFMExtract } from '$lib/utils/usfmTextExtractor.js';
  import TabIcon from '$lib/components/shared/TabIcon.svelte';

  let userInput = '';
  let isSubmitting = false;
  let sessionCost = 0;
  let messagesEndRef;
  let textareaRef;

  // Subscribe to stores
  let resources = {};
  let messages = [];
  let reference = null;

  // Store subscriptions
  const unsubscribeResources = resourcesStore.subscribe((value) => {
    resources = value;
  });

  const unsubscribeMessages = chatStore.messages.subscribe((value) => {
    messages = value;
  });

  const unsubscribeReference = resourcesStore.reference.subscribe((value) => {
    reference = value;
  });

  // Ensure all resources are active for comprehensive AI context
  onMount(() => {
    // Self-activating ALL resources for comprehensive AI context
    ['scripture', 'notes', 'questions', 'words', 'links'].forEach(resource => {
      resourcesStore.activateResource(resource);
    });
    
    // Activate AI tab when component mounts
    chatStore.activateAITab();
  });

  // Auto-scroll to bottom when new messages arrive
  afterUpdate(() => {
    if (messagesEndRef) {
      messagesEndRef.scrollIntoView({ behavior: 'smooth' });
    }
  });

  // Auto-resize textarea
  $: if (textareaRef) {
    textareaRef.style.height = 'auto';
    textareaRef.style.height = `${textareaRef.scrollHeight}px`;
  }

  // Enhanced clear messages that also resets session cost
  function clearMessages() {
    chatStore.clearMessages();
    sessionCost = 0;
  }

  // Get formatted context for LLM - ALWAYS ready and consistent
  function getFormattedContext() {
    // Extract clean scripture text for LLM at runtime from raw USFM (antifragile pattern)
    let scriptureForLLM = null;
    let scriptureMetadata = null;
    
    if (resources.scripture && reference) {
      // Raw USFM is the single source of truth - extract clean text at runtime
      const rawUsfm = resources.scripture;
      
      try {
        // Extract clean text - try chapter first for broader context, then specific verse
        let cleanText;
        let extractionMethod;
        
        try {
          // PRIMARY: Extract entire chapter with verse numbers for comprehensive LLM context
          cleanText = extractChapterText(rawUsfm, reference.chapter);
          extractionMethod = 'chapter';
        } catch (chapterError) {
          console.warn('🔍 LLM Context: Chapter extraction failed, trying single verse:', chapterError.message);
          // Fallback: Extract specific verse with verse number
          cleanText = extractVerseText(rawUsfm, reference.chapter, reference.verse);
          extractionMethod = 'verse';
        }
        
        const isClean = validateCleanText(cleanText);
        
        // If extraction returned empty or failed validation, log details
        if (!cleanText || cleanText.trim().length === 0) {
          throw new Error(`Extraction returned empty text for ${reference.citation}`);
        }
        
        if (!isClean) {
          console.warn('⚠️ LLM Context: Extracted text contains markup patterns!');
        }
        
        scriptureForLLM = cleanText;
        scriptureMetadata = {
          extractedAt: new Date().toISOString(),
          isClean,
          originalLength: rawUsfm.length,
          cleanLength: cleanText.length,
          reference: reference.citation,
          extractionMethod: extractionMethod
        };
        
      } catch (error) {
        console.error('❌ LLM Context: Failed to extract clean text from USFM:', error);
        console.error('❌ LLM Context: Error details:', error.message, error.stack);
        console.log('🚨 LLM Context: Attempting emergency fallback extraction');
        
        // EMERGENCY FALLBACK: Use simple string operations for aligned Bibles
        try {
          const emergencyText = emergencyUSFMExtract(rawUsfm, reference.chapter, reference.verse);
          if (emergencyText && emergencyText.trim().length > 0) {
            scriptureForLLM = emergencyText;
            scriptureMetadata = {
              extractedAt: new Date().toISOString(),
              isClean: false, // Emergency extraction may not be perfectly clean
              originalLength: rawUsfm.length,
              cleanLength: emergencyText.length,
              reference: reference.citation,
              extractionMethod: 'emergency',
              fallbackReason: error.message
            };
            console.log('✅ LLM Context: Emergency extraction successful');
          } else {
            throw new Error('Emergency extraction also failed');
          }
        } catch (emergencyError) {
          console.error('🚨 LLM Context: Emergency extraction failed:', emergencyError);
          
          // FINAL FALLBACK: Provide a helpful message instead of raw USFM
          scriptureForLLM = `[Scripture text for ${reference.citation} is temporarily unavailable due to formatting complexity. Translation resources are still available.]`;
          scriptureMetadata = {
            extractedAt: new Date().toISOString(),
            isClean: true,
            originalLength: rawUsfm.length,
            cleanLength: scriptureForLLM.length,
            reference: reference.citation,
            extractionMethod: 'fallback-message',
            fallbackReason: 'All extraction methods failed'
          };
          console.log('📝 LLM Context: Using fallback message for user-friendly experience');
        }
      }
    }
    
    const formattedContext = {
      reference: reference || null,
      resources: {
        scripture: scriptureForLLM,
        translationNotes: resources.notes || [],
        translationQuestions: resources.questions || [],
        translationWords: resources.words || [],
        translationWordLinks: resources.links || [],
      },
      metadata: {
        timestamp: Date.now(),
        contextSize: 0,
        resourceLoadingStatus: {
          scripture: !!scriptureForLLM,
          translationNotes: (resources.notes || []).length > 0,
          translationQuestions: (resources.questions || []).length > 0,
          translationWords: (resources.words || []).length > 0,
          translationWordLinks: (resources.links || []).length > 0,
        },
        scriptureMetadata: scriptureMetadata,
      },
    };
    
    return formattedContext;
  }

  async function handleSendMessage() {
    if (!userInput.trim() || isSubmitting) return;

    const message = userInput.trim();
    userInput = '';
    isSubmitting = true;

    // Reset textarea height
    if (textareaRef) {
      textareaRef.style.height = 'auto';
    }

    try {
      // Add user message
      chatStore.addMessage({ role: 'user', content: message });
      
      // Context is ALWAYS ready and consistent
      const formattedContext = getFormattedContext();
      
      // Send to LLM service with context
      const response = await sendChatMessage(message, formattedContext);
      
      // Handle response properly
      if (response.success) {
        // Add successful AI response
        chatStore.addMessage({ 
          role: 'assistant', 
          content: response.response,
          costEstimate: response.costEstimate,
          metadata: response.metadata
        });
        
        // Update session cost if available
        if (response.costEstimate?.totalCost) {
          sessionCost += response.costEstimate.totalCost;
        }
      } else {
        // Add error message
        chatStore.addMessage({ 
          role: 'error', 
          content: response.error || 'Unknown error occurred while processing your message.'
        });
      }
      
      // Activate AI tab to show the response
      chatStore.activateAITab();
      
    } catch (error) {
      console.error('Error sending message:', error);
      
      // Add user-friendly error message
      let errorMessage = 'Sorry, there was an error processing your message. ';
      
      if (error.message?.includes('timeout')) {
        errorMessage += 'The request timed out. Please try again with a shorter message.';
      } else if (error.message?.includes('network')) {
        errorMessage += 'Network connection issue. Please check your connection and try again.';
      } else {
        errorMessage += 'Please try again in a moment.';
      }
      
      chatStore.addMessage({ 
        role: 'error', 
        content: errorMessage
      });
    } finally {
      isSubmitting = false;
    }
  }

  function handleKeyPress(e) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  }

  function formatTimestamp(timestamp) {
    return new Date(timestamp).toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit',
    });
  }

  function formatCostDisplay(cost) {
    if (cost < 0.0001) {
      return '<$0.0001';
    }
    return `$${cost.toFixed(4)}`;
  }

  function getSessionCostColor(total) {
    if (total < 0.01) return 'session-cost-low';
    if (total < 0.1) return 'session-cost-medium';
    return 'session-cost-high';
  }

  // Handle clicking on prompt suggestions
  async function handlePromptSuggestionClick(prompt) {
    if (isSubmitting) return;
    userInput = prompt;
    // Auto-send the message
    setTimeout(() => handleSendMessage(), 100);
  }

  // Get contextual prompt suggestions based on available resources
  function getPromptSuggestions() {
    const suggestions = [
      'What are the key translation challenges for this verse?',
      'Explain the cultural context of this passage',
      'What are the important words to understand in this verse?',
    ];

    // Add resource-specific suggestions
    if ((resources.notes || []).length > 0) {
      suggestions.push('Summarize the translation notes for this verse');
    }
    
    if ((resources.questions || []).length > 0) {
      suggestions.push('What questions should translators consider?');
    }
    
    if ((resources.words || []).length > 0) {
      suggestions.push('Define the key theological terms in this passage');
    }

    return suggestions.slice(0, 6);
  }

  // Get current context info for display
  $: contextInfo = {
    reference: reference?.citation || 'No reference',
    resourceCount: (resources.scripture ? 1 : 0) +
                  (resources.notes?.length || 0) +
                  (resources.questions?.length || 0) +
                  (resources.words?.length || 0) +
                  (resources.links?.length || 0)
  };

  onDestroy(() => {
    unsubscribeResources();
    unsubscribeMessages();
    unsubscribeReference();
  });
</script>

<div class="chat-panel" data-testid="llm-chat-panel">
  <!-- Chat Header -->
  <div class="chat-header">
    <div class="header-title">
      <h3>Translation Assistant</h3>
      <span class="subtitle">Powered by AI</span>
    </div>
    <div class="header-actions">
      <div class="context-indicator" title="Current context">
        <span class="context-icon">📚</span>
        <span class="context-text">
          {contextInfo.reference} ({contextInfo.resourceCount} sources)
        </span>
      </div>
      
      {#if sessionCost > 0}
        <div class="session-cost-indicator {getSessionCostColor(sessionCost)}" title="Total conversation cost: {formatCostDisplay(sessionCost)}">
          <span class="session-cost-icon">💰</span>
          <span class="session-cost-text">{formatCostDisplay(sessionCost)}</span>
        </div>
      {/if}
      
      <button on:click={clearMessages} class="clear-button" title="Clear conversation" disabled={messages.length === 0}>🗑️</button>
    </div>
  </div>

  <!-- Welcome Message -->
  {#if messages.length === 0}
    <div class="welcome-message">
      <div class="welcome-icon">
        <TabIcon type="chat" class="tab-icon" />
      </div>
      <h4>Welcome to Translation Assistant!</h4>
      <p>I can help with translation resources. Ask me anything about:</p>
      <ul>
        <li>Translation notes and explanations</li>
        <li>Key words and their meanings</li>
        <li>Cultural and historical context</li>
        <li>Translation questions and challenges</li>
      </ul>
      
      <!-- Show current resources -->
      {#if contextInfo.resourceCount > 0}
        <div class="available-resources">
          <p><strong>Currently Available:</strong></p>
          <div class="resources-list">
            {#if resources.scripture}
              <span class="resource-tag">Scripture ✓</span>
            {/if}
            {#if (resources.notes?.length || 0) > 0}
              <span class="resource-tag">Notes ({resources.notes.length}) ✓</span>
            {/if}
            {#if (resources.questions?.length || 0) > 0}
              <span class="resource-tag">Questions ({resources.questions.length}) ✓</span>
            {/if}
            {#if (resources.words?.length || 0) > 0}
              <span class="resource-tag">Words ({resources.words.length}) ✓</span>
            {/if}
            {#if (resources.links?.length || 0) > 0}
              <span class="resource-tag">Links ({resources.links.length}) ✓</span>
            {/if}
          </div>
        </div>
      {/if}
      
      <div class="prompt-suggestions">
        <p><strong>Try asking:</strong></p>
        <div class="suggestions-list">
          {#each getPromptSuggestions() as suggestion}
            <button
              class="suggestion-button"
              on:click={() => handlePromptSuggestionClick(suggestion)}
              disabled={isSubmitting}
            >
              {suggestion}
            </button>
          {/each}
        </div>
      </div>
    </div>
  {/if}

  <!-- Messages - Only show when there are messages -->
  {#if messages.length > 0}
    <div class="messages-container">
      {#each messages as message}
        <div class="message {message.role === 'user' ? 'user-message' : 'assistant-message'} {message.role === 'error' ? 'error-message' : ''}">
          <div class="message-content">
            <div class="message-text">
              {#if message.role === 'assistant'}
                {@html processMarkdownWithRcLinks(enhanceLLMResponse(message.content, {
                  enabled: true,
                  maxEmojisPerResponse: 6,
                  excludeCategories: [],
                }), (rcLink) => {
                  // RC link clicked in chat
                })}
              {:else}
                {message.content}
              {/if}
            </div>
            <div class="message-time">
              {formatTimestamp(message.timestamp)}
              {#if message.role === 'assistant' && message.costEstimate}
                <div class="message-cost">
                  <span class="cost-badge">{formatCostDisplay(message.costEstimate.totalCost)}</span>
                </div>
              {/if}
              {#if message.metadata?.mock}
                <span class="mock-badge">MOCK</span>
              {/if}
            </div>
          </div>
        </div>
      {/each}
      
      {#if isSubmitting}
        <div class="loading-message">
          <div class="message-content">
            <div class="typing-indicator">
              <span></span>
              <span></span>
              <span></span>
            </div>
            <div class="loading-text">AI is thinking...</div>
          </div>
        </div>
      {/if}
      
      <div bind:this={messagesEndRef}></div>
    </div>
  {/if}

  <!-- Chat Input -->
  <div class="chat-input">
    <div class="input-container">
      <textarea
        bind:this={textareaRef}
        bind:value={userInput}
        on:keypress={handleKeyPress}
        placeholder="Ask about this verse..."
        class="message-input"
        disabled={isSubmitting}
        rows="1"
      />
      <button
        on:click={handleSendMessage}
        disabled={!userInput.trim() || isSubmitting}
        class="send-button"
      >
        {isSubmitting ? '⏳' : '➤'}
      </button>
    </div>
  </div>
</div>

<style>
  .chat-panel {
    display: flex;
    flex-direction: column;
    height: 100%;
    background: var(--color-panel);
    border: 1px solid var(--color-border);
    border-radius: 8px;
    overflow: hidden;
  }

  .chat-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem;
    background: var(--color-header);
    border-bottom: 1px solid var(--color-border);
    flex-shrink: 0;
  }

  .header-title h3 {
    margin: 0;
    color: var(--color-text);
    font-size: 1.1rem;
  }

  .subtitle {
    color: var(--color-text-secondary);
    font-size: 0.8rem;
  }

  .header-actions {
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .context-indicator {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.25rem 0.5rem;
    background: var(--color-secondary-alpha);
    border-radius: 4px;
    font-size: 0.8rem;
  }

  .context-icon {
    font-size: 1rem;
  }

  .context-text {
    color: var(--color-text-secondary);
  }

  .session-cost-indicator {
    display: flex;
    align-items: center;
    gap: 0.25rem;
    padding: 0.25rem 0.5rem;
    border-radius: 4px;
    font-size: 0.8rem;
    font-weight: 500;
  }

  .session-cost-low {
    background: var(--color-success-alpha);
    color: var(--color-success);
  }

  .session-cost-medium {
    background: var(--color-warning-alpha);
    color: var(--color-warning);
  }

  .session-cost-high {
    background: var(--color-error-alpha);
    color: var(--color-error);
  }

  .clear-button {
    background: transparent;
    border: none;
    color: var(--color-text-secondary);
    cursor: pointer;
    padding: 0.25rem;
    border-radius: 4px;
    font-size: 1rem;
    transition: all 0.2s ease;
  }

  .clear-button:hover:not(:disabled) {
    background: var(--color-hover);
    color: var(--color-text);
  }

  .clear-button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .welcome-message {
    flex: 1;
    padding: 2rem;
    text-align: center;
    overflow-y: auto;
  }

  .welcome-icon {
    margin-bottom: 1rem;
  }

  .welcome-message h4 {
    color: var(--color-primary);
    margin-bottom: 1rem;
  }

  .welcome-message p {
    color: var(--color-text-secondary);
    margin-bottom: 1rem;
  }

  .welcome-message ul {
    text-align: left;
    max-width: 400px;
    margin: 0 auto 2rem;
    color: var(--color-text-secondary);
  }

  .available-resources {
    margin: 2rem 0;
    padding: 1rem;
    background: var(--color-background);
    border-radius: 8px;
  }

  .resources-list {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    justify-content: center;
  }

  .resource-tag {
    background: var(--color-success-alpha);
    color: var(--color-success);
    padding: 0.25rem 0.5rem;
    border-radius: 4px;
    font-size: 0.8rem;
    font-weight: 500;
  }

  .prompt-suggestions {
    margin-top: 2rem;
  }

  .suggestions-list {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    max-width: 500px;
    margin: 0 auto;
  }

  .suggestion-button {
    background: var(--color-background);
    border: 1px solid var(--color-border);
    color: var(--color-text);
    padding: 0.8rem;
    border-radius: 6px;
    cursor: pointer;
    text-align: left;
    transition: all 0.2s ease;
  }

  .suggestion-button:hover:not(:disabled) {
    background: var(--color-hover);
    border-color: var(--color-primary);
  }

  .suggestion-button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .messages-container {
    flex: 1;
    overflow-y: auto;
    padding: 1rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .message {
    display: flex;
    flex-direction: column;
    max-width: 80%;
  }

  .user-message {
    align-self: flex-end;
  }

  .assistant-message {
    align-self: flex-start;
  }

  .error-message {
    align-self: center;
    max-width: 90%;
  }

  .message-content {
    background: var(--color-background);
    border: 1px solid var(--color-border);
    border-radius: 8px;
    padding: 0.8rem;
  }

  .user-message .message-content {
    background: var(--color-primary-alpha);
    border-color: var(--color-primary);
  }

  .error-message .message-content {
    background: var(--color-error-alpha);
    border-color: var(--color-error);
    color: var(--color-error);
  }

  .message-text {
    margin-bottom: 0.5rem;
    line-height: 1.5;
  }

  .message-time {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 0.8rem;
    color: var(--color-text-secondary);
  }

  .cost-badge {
    background: var(--color-secondary-alpha);
    color: var(--color-secondary);
    padding: 0.1rem 0.3rem;
    border-radius: 3px;
    font-size: 0.7rem;
    font-weight: 500;
  }

  .mock-badge {
    background: var(--color-warning-alpha);
    color: var(--color-warning);
    padding: 0.1rem 0.3rem;
    border-radius: 3px;
    font-size: 0.7rem;
    font-weight: 500;
  }

  .loading-message {
    align-self: flex-start;
    max-width: 80%;
  }

  .loading-message .message-content {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .typing-indicator {
    display: flex;
    gap: 0.2rem;
  }

  .typing-indicator span {
    width: 6px;
    height: 6px;
    background: var(--color-text-secondary);
    border-radius: 50%;
    animation: typing 1.4s infinite;
  }

  .typing-indicator span:nth-child(2) {
    animation-delay: 0.2s;
  }

  .typing-indicator span:nth-child(3) {
    animation-delay: 0.4s;
  }

  @keyframes typing {
    0%, 60%, 100% {
      transform: translateY(0);
    }
    30% {
      transform: translateY(-10px);
    }
  }

  .loading-text {
    color: var(--color-text-secondary);
    font-style: italic;
    font-size: 0.9rem;
  }

  .chat-input {
    padding: 1rem;
    border-top: 1px solid var(--color-border);
    background: var(--color-header);
    flex-shrink: 0;
  }

  .input-container {
    display: flex;
    gap: 0.5rem;
    align-items: end;
  }

  .message-input {
    flex: 1;
    padding: 0.8rem;
    border: 1px solid var(--color-border);
    border-radius: 6px;
    background: var(--color-background);
    color: var(--color-text);
    font-family: inherit;
    font-size: 0.9rem;
    resize: none;
    min-height: 44px;
    max-height: 120px;
    overflow-y: auto;
  }

  .message-input:focus {
    outline: none;
    border-color: var(--color-primary);
  }

  .message-input:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .send-button {
    background: var(--color-primary);
    color: white;
    border: none;
    border-radius: 6px;
    padding: 0.8rem 1rem;
    cursor: pointer;
    font-size: 1rem;
    min-width: 44px;
    height: 44px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s ease;
  }

  .send-button:hover:not(:disabled) {
    background: var(--color-primary-hover);
    transform: translateY(-1px);
  }

  .send-button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  /* Responsive design */
  @media (max-width: 768px) {
    .chat-header {
      flex-direction: column;
      gap: 0.5rem;
      align-items: flex-start;
    }

    .header-actions {
      width: 100%;
      justify-content: space-between;
    }

    .welcome-message {
      padding: 1rem;
    }

    .message {
      max-width: 95%;
    }

    .suggestions-list {
      max-width: 100%;
    }

    .resources-list {
      flex-direction: column;
    }
  }
</style>

// src-new/components/LLMChatPanel.jsx
/**
 * LLMChatPanel.jsx
 * Main chat interface component for LLM translation assistance
 */

import React, { useState, useRef, useEffect } from "react";
import { useChat } from "../context/ChatContext";
import { MarkdownWithRcLinks } from "../utils/markdownUtils";
import { enhanceLLMResponse } from "../utils/emojiEnhancer";
import styles from "./LLMChatPanel.module.css";

export function LLMChatPanel({ reference }) {
  const [inputMessage, setInputMessage] = useState("");
  const messagesEndRef = useRef(null);
  const textareaRef = useRef(null);

  const {
    chatHistory,
    isLoading,
    error,
    sendMessage,
    clearChat,
    getContextInfo,
    areResourcesReady,
    getResourceStatus,
    resourceChangeNotification,
    dismissResourceChangeNotification,
    startNewConversation,
    sessionCost,
    getSessionCostInfo,
  } = useChat();

  // Get resource status for UI display
  const resourceStatus = getResourceStatus();

  // Auto-scroll to bottom when new messages arrive
  useEffect(() => {
    // Check if scrollIntoView exists (not available in JSDOM test environment)
    if (messagesEndRef.current?.scrollIntoView) {
      messagesEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [chatHistory]);

  // Auto-resize textarea
  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
    }
  }, [inputMessage]);

  const handleSendMessage = async () => {
    if (!inputMessage.trim() || isLoading || !areResourcesReady()) return;

    const message = inputMessage.trim();
    setInputMessage("");

    // Reset textarea height
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
    }

    await sendMessage(message);
  };

  const handleKeyPress = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const formatTimestamp = (timestamp) => {
    return new Date(timestamp).toLocaleTimeString([], {
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const formatCostDisplay = (cost) => {
    if (cost < 0.0001) {
      return "<$0.0001";
    }
    return `$${cost.toFixed(4)}`;
  };

  const getCostColor = (cost) => {
    if (cost < 0.01) return styles.costLow;
    if (cost < 0.1) return styles.costMedium;
    return styles.costHigh;
  };

  const getSessionCostColor = (total) => {
    if (total < 0.01) return styles.sessionCostLow;
    if (total < 0.1) return styles.sessionCostMedium;
    return styles.sessionCostHigh;
  };

  const renderMessage = (message) => {
    const isUser = message.type === "user";
    const isError = message.type === "error";
    const isAssistant = message.type === "assistant";

    return (
      <div
        key={message.id}
        className={`${styles.message} ${isUser ? styles.userMessage : styles.assistantMessage} ${
          isError ? styles.errorMessage : ""
        }`}
      >
        <div className={styles.messageContent}>
          <div className={styles.messageText}>
            {isAssistant ? (
              <MarkdownWithRcLinks
                content={enhanceLLMResponse(message.content, {
                  enabled: true,
                  maxEmojisPerResponse: 6,
                  excludeCategories: [],
                })}
                onRcLinkClick={(rcLink) => {
                  // Handle RC link clicks in chat context if needed
                  console.log("RC link clicked in chat:", rcLink);
                }}
              />
            ) : (
              message.content
            )}
          </div>
          <div className={styles.messageTime}>
            {formatTimestamp(message.timestamp)}
            {isAssistant && message.costEstimate && (
              <div
                className={`${styles.messageCost} ${getCostColor(message.costEstimate.totalCost)}`}
                title={`Message Cost Breakdown
Context: ${message.costEstimate.contextSize}
Input: ${message.costEstimate.estimatedInputTokens.toLocaleString()} tokens ($${message.costEstimate.inputCost.toFixed(
                  4
                )})
Output: ${message.costEstimate.estimatedOutputTokens.toLocaleString()} tokens ($${message.costEstimate.outputCost.toFixed(
                  4
                )})
Total: ${formatCostDisplay(message.costEstimate.totalCost)}

Resources Used:
${message.costEstimate.resources.scripture === "✓" ? "✓" : "✗"} Scripture
${message.costEstimate.resources.translationNotes ? "✓" : "✗"} Notes (${
                  message.costEstimate.resources.translationNotes
                })
${message.costEstimate.resources.translationQuestions ? "✓" : "✗"} Questions (${
                  message.costEstimate.resources.translationQuestions
                })
${message.costEstimate.resources.translationWords ? "✓" : "✗"} Words (${
                  message.costEstimate.resources.translationWords
                })
${message.costEstimate.resources.translationWordLinks ? "✓" : "✗"} Links (${
                  message.costEstimate.resources.translationWordLinks
                })

Model: ${message.costEstimate.model}`}
              >
                💰 {formatCostDisplay(message.costEstimate.totalCost)}
              </div>
            )}
            {message.metadata?.mock && <span className={styles.mockBadge}>MOCK</span>}
          </div>
        </div>
      </div>
    );
  };

  const contextInfo = getContextInfo();

  return (
    <div className={styles.chatPanel} data-testid='llm-chat-panel'>
      {/* Chat Header */}
      <div className={styles.chatHeader}>
        <div className={styles.headerTitle}>
          <h3>Translation Assistant</h3>
          <span className={styles.subtitle}>Powered by AI</span>
        </div>
        <div className={styles.headerActions}>
          {resourceStatus?.ready && contextInfo && (
            <div className={styles.contextIndicator} title='Current context loaded'>
              <span className={styles.contextIcon}>📚</span>
              <span className={styles.contextText}>
                {contextInfo.reference} ({contextInfo.resourceCount} resources)
              </span>
            </div>
          )}
          {resourceStatus?.loading && (
            <div className={styles.loadingIndicator} title='Loading translation resources...'>
              <span className={styles.loadingIcon}>⏳</span>
              <span className={styles.loadingText}>Loading resources...</span>
            </div>
          )}
          {sessionCost.total > 0 && (
            <div
              className={`${styles.sessionCostIndicator} ${getSessionCostColor(sessionCost.total)}`}
              title={`Session Cost Summary
Messages: ${sessionCost.messageCount} AI responses
Total Input: ${sessionCost.totalTokens.input.toLocaleString()} tokens
Total Output: ${sessionCost.totalTokens.output.toLocaleString()} tokens
Total Cost: ${formatCostDisplay(sessionCost.total)}
Average/Message: ${formatCostDisplay(
                sessionCost.messageCount > 0 ? sessionCost.total / sessionCost.messageCount : 0
              )}

Model: GPT-4o-mini`}
            >
              <span className={styles.sessionCostIcon}>💰</span>
              <span className={styles.sessionCostText}>{formatCostDisplay(sessionCost.total)}</span>
            </div>
          )}
          <button
            onClick={clearChat}
            className={styles.clearButton}
            title='Clear conversation'
            disabled={chatHistory.length === 0}
          >
            🗑️
          </button>
        </div>
      </div>

      {/* Resource Change Notification */}
      {resourceChangeNotification && (
        <div className={styles.resourceChangeNotification}>
          <div className={styles.notificationContent}>
            <span className={styles.notificationIcon}>🔄</span>
            <div className={styles.notificationText}>
              <strong>Reference Changed</strong>
              <p>
                From {resourceChangeNotification.previousReference} to{" "}
                {resourceChangeNotification.newReference}
              </p>
              <p>Would you like to start a new conversation with the updated resources?</p>
            </div>
            <div className={styles.notificationActions}>
              <button onClick={startNewConversation} className={styles.primaryButton}>
                Start New Chat
              </button>
              <button
                onClick={dismissResourceChangeNotification}
                className={styles.secondaryButton}
              >
                Continue Current
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Resource Loading Status */}
      {!resourceStatus?.ready && resourceStatus?.loading && (
        <div className={styles.resourceLoadingStatus}>
          <div className={styles.loadingHeader}>
            <span className={styles.loadingIcon}>📚</span>
            <span>Loading Translation Resources...</span>
          </div>
          <div className={styles.resourceDetails}>
            <div className={styles.resourceItem}>
              <span className={resourceStatus.details.scripture ? styles.ready : styles.loading}>
                {resourceStatus.details.scripture ? "✓" : "⏳"}
              </span>
              <span>Scripture Text</span>
              {resourceStatus.resourceCounts?.scripture > 0 && (
                <span className={styles.count}>({resourceStatus.resourceCounts.scripture})</span>
              )}
            </div>
            <div className={styles.resourceItem}>
              <span
                className={resourceStatus.details.translationNotes ? styles.ready : styles.loading}
              >
                {resourceStatus.details.translationNotes ? "✓" : "⏳"}
              </span>
              <span>Translation Notes</span>
              {resourceStatus.resourceCounts?.translationNotes > 0 && (
                <span className={styles.count}>
                  ({resourceStatus.resourceCounts.translationNotes})
                </span>
              )}
            </div>
            <div className={styles.resourceItem}>
              <span
                className={
                  resourceStatus.details.translationQuestions ? styles.ready : styles.loading
                }
              >
                {resourceStatus.details.translationQuestions ? "✓" : "⏳"}
              </span>
              <span>Translation Questions</span>
              {resourceStatus.resourceCounts?.translationQuestions > 0 && (
                <span className={styles.count}>
                  ({resourceStatus.resourceCounts.translationQuestions})
                </span>
              )}
            </div>
            <div className={styles.resourceItem}>
              <span
                className={resourceStatus.details.translationWords ? styles.ready : styles.loading}
              >
                {resourceStatus.details.translationWords ? "✓" : "⏳"}
              </span>
              <span>Translation Words</span>
              {resourceStatus.resourceCounts?.translationWords > 0 && (
                <span className={styles.count}>
                  ({resourceStatus.resourceCounts.translationWords})
                </span>
              )}
            </div>
            <div className={styles.resourceItem}>
              <span
                className={
                  resourceStatus.details.translationWordLinks ? styles.ready : styles.loading
                }
              >
                {resourceStatus.details.translationWordLinks ? "✓" : "⏳"}
              </span>
              <span>Translation Word Links</span>
              {resourceStatus.resourceCounts?.translationWordLinks > 0 && (
                <span className={styles.count}>
                  ({resourceStatus.resourceCounts.translationWordLinks})
                </span>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Welcome Message */}
      {chatHistory.length === 0 && resourceStatus?.ready && (
        <div className={styles.welcomeMessage}>
          <div className={styles.welcomeIcon}>🤖</div>
          <h4>Welcome to Translation Assistant!</h4>
          <p>
            I have access to all translation resources for the current verse. Ask me anything about:
          </p>
          <ul>
            <li>Translation notes and explanations</li>
            <li>Key words and their meanings</li>
            <li>Cultural and historical context</li>
            <li>Translation questions and challenges</li>
          </ul>
          <div className={styles.availableResources}>
            <p>
              <strong>Available Resources:</strong>
            </p>
            <div className={styles.resourcesList}>
              {resourceStatus.resourceCounts?.scripture > 0 && (
                <span className={styles.resourceTag}>Scripture ✓</span>
              )}
              {resourceStatus.resourceCounts?.translationNotes > 0 && (
                <span className={styles.resourceTag}>
                  Notes ({resourceStatus.resourceCounts.translationNotes}) ✓
                </span>
              )}
              {resourceStatus.resourceCounts?.translationQuestions > 0 && (
                <span className={styles.resourceTag}>
                  Questions ({resourceStatus.resourceCounts.translationQuestions}) ✓
                </span>
              )}
              {resourceStatus.resourceCounts?.translationWords > 0 && (
                <span className={styles.resourceTag}>
                  Words ({resourceStatus.resourceCounts.translationWords}) ✓
                </span>
              )}
              {resourceStatus.resourceCounts?.translationWordLinks > 0 && (
                <span className={styles.resourceTag}>
                  Links ({resourceStatus.resourceCounts.translationWordLinks}) ✓
                </span>
              )}
            </div>
          </div>
          <p className={styles.promptSuggestion}>
            Try asking: "What are the key translation challenges for this verse?"
          </p>
        </div>
      )}

      {/* Resources Not Ready Message */}
      {chatHistory.length === 0 && !resourceStatus?.ready && !resourceStatus?.loading && (
        <div className={styles.notReadyMessage}>
          <div className={styles.notReadyIcon}>⚠️</div>
          <h4>Resources Not Available</h4>
          <p>
            Translation resources are not currently available for this verse. Please check your
            connection or try a different verse.
          </p>
          {resourceStatus?.error && (
            <div className={styles.errorDetails}>
              <strong>Error:</strong> {resourceStatus.error}
            </div>
          )}
        </div>
      )}

      {/* Chat Messages */}
      <div className={styles.messagesContainer}>
        {chatHistory.map(renderMessage)}
        {isLoading && (
          <div className={styles.loadingMessage}>
            <div className={styles.messageContent}>
              <div className={styles.typingIndicator}>
                <span></span>
                <span></span>
                <span></span>
              </div>
              <div className={styles.loadingText}>AI is thinking...</div>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Error Display */}
      {error && (
        <div className={styles.errorBanner}>
          <span className={styles.errorIcon}>⚠️</span>
          <span className={styles.errorText}>{error}</span>
        </div>
      )}

      {/* Chat Input */}
      <div className={styles.chatInput}>
        <div className={styles.inputContainer}>
          <textarea
            ref={textareaRef}
            value={inputMessage}
            onChange={(e) => setInputMessage(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder={
              !areResourcesReady()
                ? "Waiting for translation resources to load..."
                : "Ask about translation notes, word meanings, context..."
            }
            className={styles.messageInput}
            disabled={isLoading || !areResourcesReady()}
            rows={1}
            maxLength={4000}
          />
          <button
            onClick={handleSendMessage}
            className={styles.sendButton}
            disabled={!inputMessage.trim() || isLoading || !areResourcesReady()}
            title={
              !areResourcesReady() ? "Waiting for resources to load..." : "Send message (Enter)"
            }
          >
            {isLoading ? (
              <span className={styles.loadingSpinner}>⏳</span>
            ) : !areResourcesReady() ? (
              <span className={styles.waitingSpinner}>⏳</span>
            ) : (
              <span className={styles.sendIcon}>➤</span>
            )}
          </button>
        </div>
        <div className={styles.inputFooter}>
          <span className={styles.charCount}>{inputMessage.length}/4000</span>
          {import.meta.env.VITE_USE_MOCK_CHAT === "true" && (
            <span className={styles.devIndicator}>Using Mock Responses</span>
          )}
        </div>
      </div>
    </div>
  );
}

export default LLMChatPanel;
