// src-new/components/MainView.jsx
/**
 * MainView.jsx
 * Orchestrates the main content area including scripture text, navigation tabs, and helps panels.
 */

import React, { useContext, useState, useRef, createContext } from "react";
import { ReferenceContext } from "../context/ReferenceContext";
import { ManifestsContext } from "../context/MultiManifestsContext";

import { ScripturePanel } from "./ScripturePanel";
import { HelpsTabs } from "./HelpsTabs";
import { convertRcUriToUrl } from "../utils/rcLinkUtils.jsx";
import { getArticle } from "../services/twService";
import { getArticle as getTaArticle } from "../services/taService";
import styles from "./MainView.module.css";

// Context for rc:// link handling
export const RcLinkContext = createContext();

export function MainView() {
  const { reference, organization, languageId } = useContext(ReferenceContext);
  const { manifests } = useContext(ManifestsContext);
  const [activeHelpsTab, setActiveHelpsTab] = useState("tn");
  const [activeMobileTab, setActiveMobileTab] = useState("scripture");
  const helpsTabsRef = useRef();

  const handleVerseClick = (verseNum) => {
    // When a verse is clicked, it automatically updates the reference context
    // which triggers the helps panels to update
    console.log("Verse clicked:", verseNum);
  };

  // Handle rc:// link clicks to open article tabs or switch to appropriate internal tabs
  const handleRcLinkClick = async (rcUri, contextLanguageId, contextOrganization) => {
    if (!rcUri || !rcUri.startsWith("rc://")) {
      console.warn("Invalid rc:// URI:", rcUri);
      return;
    }

    // Use provided context or fall back to default context
    const effectiveLanguageId = contextLanguageId || languageId || "en";
    const effectiveOrganization = contextOrganization || organization || "unfoldingWord";

    // Parse the rc:// URI to determine the appropriate tab
    const uriParts = rcUri.split("/");
    if (uriParts.length < 4) {
      console.warn("Malformed rc:// URI:", rcUri);
      return;
    }

    const resourceType = uriParts[3]; // tw, tn, tq, etc.

    switch (resourceType) {
      case "tw":
        // For translation words, fetch the full article and open in new tab
        try {
          const article = await getArticle(rcUri, effectiveLanguageId, effectiveOrganization);
          if (article && helpsTabsRef.current) {
            helpsTabsRef.current.openArticleTab({
              id: rcUri.replace(/[^a-zA-Z0-9]/g, "_"),
              title: article.title,
              content: article.content,
              rcUri: rcUri,
              error: article.error,
            });
          } else {
            console.warn("Could not fetch article for rc:// URI:", rcUri);
            // Fallback to switching to tw tab
            if (helpsTabsRef.current) {
              helpsTabsRef.current.switchToTab("tw");
            }
          }
        } catch (error) {
          console.error("Error fetching article:", error);
          // Fallback to switching to tw tab
          if (helpsTabsRef.current) {
            helpsTabsRef.current.switchToTab("tw");
          }
        }
        break;
      case "tn":
        // For translation notes, switch to tn tab
        if (helpsTabsRef.current) {
          helpsTabsRef.current.switchToTab("tn");
        }
        break;
      case "tq":
        // For translation questions, switch to tq tab
        if (helpsTabsRef.current) {
          helpsTabsRef.current.switchToTab("tq");
        }
        break;
      case "ta":
        // For Translation Academy, fetch the actual article and open in new tab
        try {
          const article = await getTaArticle(rcUri, effectiveLanguageId, effectiveOrganization);
          if (article && helpsTabsRef.current) {
            helpsTabsRef.current.openArticleTab({
              id: rcUri.replace(/[^a-zA-Z0-9]/g, "_"),
              title: article.title,
              content: article.content,
              rcUri: rcUri,
              error: article.error,
            });
          } else {
            console.warn("Could not fetch Translation Academy article for rc:// URI:", rcUri);
            // Fallback to external link
            const externalUrl = convertRcUriToUrl(
              rcUri,
              effectiveLanguageId,
              effectiveOrganization
            );
            if (externalUrl) {
              console.log("Opening external resource:", externalUrl);
              window.open(externalUrl, "_blank", "noopener,noreferrer");
            }
          }
        } catch (error) {
          console.error("Error fetching Translation Academy article:", error);
          // Fallback to external link
          const externalUrl = convertRcUriToUrl(rcUri, effectiveLanguageId, effectiveOrganization);
          if (externalUrl) {
            console.log("Opening external resource:", externalUrl);
            window.open(externalUrl, "_blank", "noopener,noreferrer");
          }
        }
        break;
      default:
        // For other external resources, open in new tab
        const externalUrl = convertRcUriToUrl(rcUri, effectiveLanguageId, effectiveOrganization);
        if (externalUrl) {
          console.log("Opening external resource:", externalUrl);
          window.open(externalUrl, "_blank", "noopener,noreferrer");
        } else {
          console.warn("Could not convert rc:// URI to external URL:", rcUri);
        }
        break;
    }
  };

  return (
    <main data-testid='main-view' className={styles.mainView}>
      {/* Mobile Tab Navigation */}
      <div className={styles.mobileTabNav}>
        <button
          className={`${styles.mobileTab} ${
            activeMobileTab === "scripture" ? styles.mobileTabActive : ""
          }`}
          onClick={() => setActiveMobileTab("scripture")}
        >
          Scripture
        </button>
        <button
          className={`${styles.mobileTab} ${
            activeMobileTab === "resources" ? styles.mobileTabActive : ""
          }`}
          onClick={() => setActiveMobileTab("resources")}
        >
          Resources
        </button>
      </div>

      {/* Main Content Area */}
      <div className={styles.contentArea}>
        {/* Scripture Panel */}
        <div
          className={`${styles.scripturePanel} ${
            activeMobileTab === "scripture" ? styles.mobilePanelActive : ""
          }`}
        >
          <ScripturePanel reference={reference} onVerseClick={handleVerseClick} />
        </div>

        {/* Translation Helps */}
        <div
          className={`${styles.helpsPanel} ${
            activeMobileTab === "resources" ? styles.mobilePanelActive : ""
          }`}
        >
          <RcLinkContext.Provider value={{ handleRcLinkClick }}>
            <HelpsTabs ref={helpsTabsRef} reference={reference} />
          </RcLinkContext.Provider>
        </div>
      </div>
    </main>
  );
}

// svelte-migration/src/lib/components/MainView.svelte
<script>
  import { reference, organization, languageId, updateContext } from '$stores/reference.js';
  import { activateResource } from '$stores/resources.js';
  import ScripturePanel from './ScripturePanel.svelte';
  import HelpsTabs from './HelpsTabs.svelte';
  import NavigationBar from './NavigationBar.svelte';
  
  let activeHelpsTab = "tn";
  let activeMobileTab = "scripture";
  let helpsTabsRef;

  function handleVerseClick(verseNum) {
    // Verse clicks are now pure CSS highlighting operations
    console.log("Verse clicked:", verseNum, "(highlighting handled locally)");
  }

  // Handle rc:// link clicks to open article tabs or switch to appropriate internal tabs
  async function handleRcLinkClick(rcUri, contextLanguageId, contextOrganization) {
    if (!rcUri || !rcUri.startsWith("rc://")) {
      console.warn("Invalid rc:// URI:", rcUri);
      return;
    }

    // Use provided context or fall back to default context
    const effectiveLanguageId = contextLanguageId || $languageId || "en";
    const effectiveOrganization = contextOrganization || $organization || "unfoldingWord";

    // Parse the rc:// URI to determine the appropriate tab
    const uriParts = rcUri.split("/");
    if (uriParts.length < 4) {
      console.warn("Malformed rc:// URI:", rcUri);
      return;
    }

    const rcLanguageId = uriParts[2]; // Language from RC link
    const resourceType = uriParts[3]; // tw, tn, tq, etc.
    const rcPath = uriParts[4]; // help, kt, etc.

    // Check if this is a resource selection RC link (has /help/ path)
    const isResourceSelection = rcPath === 'help' && uriParts.length >= 7;
    
    if (isResourceSelection) {
      console.log('🔗 Handling resource selection RC link:', rcUri);
      
      // Map external resource IDs to internal resource types
      const resourceTypeMap = {
        'tn': 'notes',
        'tq': 'questions', 
        'tw': 'words',
        'twl': 'links',
        'ta': 'ta'
      };
      
      const internalResourceType = resourceTypeMap[resourceType] || resourceType;
      
      console.log('📍 Setting mixed resource:', {
        externalType: resourceType,
        internalType: internalResourceType,
        languageId: rcLanguageId,
        organization: effectiveOrganization
      });
      
      // Update mixed resources configuration
      updateContext({
        mixedResources: {
          [internalResourceType]: {
            languageId: rcLanguageId,
            organization: effectiveOrganization,
            resourceId: resourceType
          }
        }
      });
      
      // Trigger resource reload with new configuration
      activateResource(internalResourceType);
      console.log(`Resource ${internalResourceType} activated and will reload with new configuration`);
      
      return;
    }

    switch (resourceType) {
      case "tw":
        // For translation words, fetch the full article and open in new tab
        try {
          console.log("Fetching TW article for:", rcUri);
          // TODO: Implement article loading
          // const article = await getArticle(rcUri, effectiveLanguageId, effectiveOrganization);
          
          // if (article && !article.error && helpsTabsRef) {
          //   console.log("Opening TW article in new tab:", article.title);
          //   helpsTabsRef.openArticleTab(article);
          // }
        } catch (error) {
          console.error("Error handling TW link:", error);
        }
        break;
      case "tn":
        console.log("Translation Notes resource will self-activate");
        break;
      case "tq":
        console.log("Translation Questions resource will self-activate");
        break;
      case "ta":
        // TODO: Implement Translation Academy article loading
        console.log("Translation Academy link:", rcUri);
        break;
      default:
        // For other external resources, open in new tab
        console.log("Opening external resource:", rcUri);
        break;
    }
  }

  // Provide rc link handler to child components
  import { setContext } from 'svelte';
  setContext('rcLinkHandler', handleRcLinkClick);
</script>

<main data-testid="main-view" class="main-view">
  <!-- Navigation Bar -->
  <NavigationBar />
  
  <!-- Mobile Tab Navigation -->
  <div class="mobile-tab-nav">
    <button
      class="mobile-tab"
      class:mobile-tab-active={activeMobileTab === "scripture"}
      on:click={() => activeMobileTab = "scripture"}
    >
      Scripture
    </button>
    <button
      class="mobile-tab"
      class:mobile-tab-active={activeMobileTab === "resources"}
      on:click={() => activeMobileTab = "resources"}
    >
      Resources
    </button>
  </div>
  
  <!-- Main Content Area -->
  <div class="content-area">
    <!-- Scripture Panel -->
    <div
      class="scripture-panel"
      class:mobile-panel-active={activeMobileTab === "scripture"}
    >
      <ScripturePanel {reference} {handleVerseClick} />
    </div>

    <!-- Translation Helps -->
    <div
      class="helps-panel"
      class:mobile-panel-active={activeMobileTab === "resources"}
    >
      <HelpsTabs bind:this={helpsTabsRef} {reference} />
    </div>
  </div>
</main>

<style>
  .main-view {
    display: flex;
    flex-direction: column;
    height: 100vh;
    background-color: var(--color-background);
    color: var(--color-text);
  }

  .mobile-tab-nav {
    display: flex;
    background-color: var(--color-surface);
    border-bottom: 1px solid var(--color-border);
    position: sticky;
    top: 0;
    z-index: 10;
  }

  .mobile-tab {
    flex: 1;
    padding: var(--spacing-3);
    border: none;
    background: transparent;
    color: var(--color-text-secondary);
    font-size: var(--font-size-md);
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .mobile-tab:hover {
    background-color: var(--color-surface-hover);
    color: var(--color-text);
  }

  .mobile-tab-active {
    color: var(--color-primary);
    background-color: var(--color-surface-secondary);
    border-bottom: 2px solid var(--color-primary);
  }

  .content-area {
    display: flex;
    flex: 1;
    overflow: hidden;
  }

  .scripture-panel,
  .helps-panel {
    flex: 1;
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  .scripture-panel {
    border-right: 1px solid var(--color-border);
  }

  /* Mobile responsive design */
  @media (max-width: 768px) {
    .mobile-tab-nav {
      display: flex;
    }

    .content-area {
      position: relative;
    }

    .scripture-panel,
    .helps-panel {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      opacity: 0;
      transform: translateX(100%);
      transition: all var(--transition-normal);
      pointer-events: none;
    }

    .mobile-panel-active {
      opacity: 1;
      transform: translateX(0);
      pointer-events: auto;
    }

    .scripture-panel {
      border-right: none;
    }
  }

  /* Desktop design */
  @media (min-width: 769px) {
    .mobile-tab-nav {
      display: none;
    }

    .scripture-panel,
    .helps-panel {
      position: static;
      opacity: 1;
      transform: none;
      pointer-events: auto;
    }
  }
</style>
